import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Actiontab from "./components/Actiontab";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
          <div className="flex h-full container mx-auto">
            <div className="flex-initial">
              <Actiontab/>
            </div>
            <div className="flex-auto ml-2 mt-2">
              {children}
            </div>
          </div>
        </body>
    </html>
  );
}
